name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Check Pull Request
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: run git diff
        run: git diff --name-only HEAD
        shell: bash

        
      - name: Check for required functions
        run: |
          for file in $(git diff --name-only HEAD); do
            if grep -qE "function (__besman_init|__besman_execute|__besman_prepare|__besman_publish|__besman_cleanup)" "$file"; then
              echo "All required functions found in $file"
            else
              echo "One or more required functions not found in $file"
              exit 1
            fi
          done
        shell: bash
