name: Sanity Check

on:
  pull_request:
    branches:
      - dev

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo change_branch
        run: echo "${{ env.CHANGE_BRANCH }}"
      - name: Run sanity checks
        run: |
          # Install dependencies or setup environment if required
          branch_name=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
          # Set the BRANCH_NAME environment variable
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
          # Run the function check script
          bash .github/scripts/sanity_checks.sh

