name: Sanity Check

on:
  pull_request:
    branches:
      - dev

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set branch name
        run: |
          branch_name=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
          echo "Branch name: $BRANCH_NAME"

      - name: Run sanity checks
        run: |
          # Install dependencies or setup environment if required
          source .github/scripts/sanity_checks.sh