name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_files:
    name: Check Modified Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # Checkout the code from the source branch of the pull request

      # - name: Install required packages
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y grep
      
      # - name: perform fetch
      #   run: git fetch

      - name: branch name
        run: git branch | grep "*"

      # - name: Get list of modified files
      #   id: get_files
      #   run: |
      #     echo "::set-output name=files::$(git diff --name-only ${{ github.event.pull_request.base.ref }}...${{ github.event.pull_request.head.ref }})"
      
      - name: Get the list of required functions
        run: cat ~/scripts/playbook_functions.txt

      # - name: Check for required functions
      #   run: |
      #     for file in $(git ls-files | grep '\-playbook\.sh$'); do
      #       # Check if the file ends with "-playbook.sh"
      #       if ! grep -q -w "function __besman_init"
      #       then
      #         echo "Missing function "
      #     done
